#!/bin/sh -ex

STORAGE=/srv/storage
PASSWORD=turnkey

mkdir -p $STORAGE/incoming
mkdir -p $STORAGE/quarantine
mkdir -p $STORAGE/download

chown -R debian-transmission:users $STORAGE/incoming
chown -R debian-transmission:users $STORAGE/quarantine
chown -R debian-transmission:users $STORAGE/download

mkdir /var/log/rtorrent

# configure transmission
CONF=/etc/transmission-daemon/settings.json
sed -i 's|"download-dir": .*|"download-dir": "\/srv\/storage\/download",|' $CONF

# configure clamav
CONF=/etc/clamav/clamd.conf
sed -i 's|\(ScanMail\) true|\1 false|; s|\(LogSyslog\) false|\1 true|' $CONF

# configure samba
CONF=/etc/samba/smb.conf
NETBIOS_NAME=$(echo $HOSTNAME | tr [a-z] [A-Z])
sed -i "s|\(netbios name =\) \(.*\)|\1 $NETBIOS_NAME|" $CONF
sed -i "s|\(server string =\) \(.*\)|\1 $CREDIT_ANCHORTEXT|" $CONF

# Rename the file server for WebDAVCGI
sed -i 's/FILESERVER/TORRENTSERVER/' /var/www/webdavcgi/webdav.conf

# Apache config
echo 'Listen 12322' >> /etc/apache2/ports.conf

a2enmod proxy_http
a2dissite 000-default
a2ensite tkl-webcp
a2ensite webdavcgi
a2ensite transmission

# initscript
update-rc.d transmission-daemon defaults 99
