#!/bin/bash -e
# set torrentserver related passwords

. /etc/default/inithooks

set +x
[ -e "$INITHOOKS_CONF" ] && . "$INITHOOKS_CONF"
printf '%s' "$APP_PASS" | "$INITHOOKS_PATH/bin/torrentserver.py" --pass-stdin
unset APP_PASS
set -x
